Add git to container; Update to latest sbt-extras.
tozny/docker-sbt-extras pull request #1
Opened 2017-04-18 21:30 UTC by m4dc4p

SBT supports `git` URLs, so the container needs a git executable.

2017-04-18 22:40 UTC, ericmann approved these changes
Not opposed to adding Git support, just worried about how Git will have access to keys for cloning repos from _inside_ the container ...

2017-04-19 01:11 UTC, fernviridian requested changes
Agree with @ericmann that we should probably find another way since we would need git, ssh, and private ssh keys tied to someone's github account....all in a docker ooey-gooey mess.

2017-04-20 02:59 UTC, m4dc4p commented
Adding git/ssh will still allow public repos to be cloned, and we can clone private repos using ssh-agent tricks. So no private keys required.

I think this is really useful, so let's discuss.

2017-04-20 16:35 UTC, fernviridian approved these changes
LGTM

2017-04-20 17:19 UTC, merged